Repository NNPDF/pineko, pull requests merged in 2022-07, with the labels that each got.

#19 Scale Variations
  .github/CODE_OF_CONDUCT.md
  .pre-commit-config.yaml
  README.md
  data/grids/load.sh
  poetry.lock
  pyproject.toml
  src/pineko/__init__.py
  src/pineko/check.py
  src/pineko/cli/__init__.py
  src/pineko/cli/_base.py
  src/pineko/cli/check.py
  src/pineko/cli/compare.py
  src/pineko/cli/convolute.py
  src/pineko/cli/opcard.py
  src/pineko/cli/theory_.py
  src/pineko/comparator.py
  src/pineko/configs.py
  src/pineko/evolve.py
  src/pineko/parser.py
  src/pineko/theory.py
  src/pineko/theory_card.py
Labels: enhancement

#24 Allow pineko to check if the grid contains SV
  src/pineko/check.py
  src/pineko/cli/__init__.py
  src/pineko/cli/check.py
  src/pineko/cli/convolute.py
  src/pineko/evolve.py
  src/pineko/theory.py
  tests/test_check.py
Labels: enhancement

#27 Change max_as during FONLL-B DIS fk calculation
  src/pineko/check.py
  src/pineko/theory.py
  tests/test_check.py
Labels: bug

#30 Check also first element in lumi for is_fonllb
  src/pineko/check.py
  tests/test_check.py
Labels: bug

#31 Splitting the func islepton and updating test
  src/pineko/check.py
  tests/test_check.py
Labels: refactor
