Repository NNPDF/pineko, pull requests merged in 2023-03, with the labels that each got.

#82 Fix sv schemes
  .github/workflows/unittests.yml
  src/pineko/evolve.py
Labels: bug

#86 Adding regression tests to Pineko
  tests/regression_data/INTEGXT3.npy
  tests/regression_data/LHCBWZMU8TEV.npy
  tests/test_regression.py
Labels: enhancement

#84 Update the calls to axes to evolve_info
  benchmarks/bench_checks.py
  poetry.lock
  pyproject.toml
  src/pineko/check.py
  src/pineko/cli/check.py
  src/pineko/evolve.py
Labels: refactor
