Repository NNPDF/pineko, pull requests merged in 2024-03, with the labels that each got.

#158 Allow evolution of fragmentation functions grids
  src/pineko/evolve.py
Labels: enhancement

#153 Automatise numerical FONLL
  docs/Makefile
  docs/source/index.rst
  docs/source/overview/prerequisites.rst
  docs/source/overview/running.rst
  docs/source/shared/abbreviations.rst
  docs/source/theory/fktables.rst
  docs/source/theory/fonll.rst
  docs/source/theory/kfactors.rst
  docs/source/theory/scalevar.rst
  src/pineko/cli/_base.py
  src/pineko/cli/fonll.py
  src/pineko/cli/scaffold.py
  src/pineko/cli/theory_.py
  src/pineko/fonll.py
  src/pineko/theory.py
  tests/test_fonll.py
Labels: documentation, enhancement

#163 Update fonll docstr and json loading
  src/pineko/fonll.py
Labels: bug

#159 Use the NNPDF data instead of yamldb
  .github/workflows/bench.yml
  .github/workflows/unittests.yml
  docs/source/overview/prerequisites.rst
  poetry.lock
  pyproject.toml
  src/pineko/configs.py
  src/pineko/fonll.py
  src/pineko/theory.py
  src/pineko/utils.py
  tests/test_utils.py
Labels: enhancement
